package com.hfad.vdials;

import android.graphics.drawable.RippleDrawable;

import java.util.HashMap;
import java.util.Map;

public class Dials{
    private Map<String, Maneuver[]> fleet = new HashMap<String, Maneuver[]>();
    public Dials(){
        this.buildDials();
    }
    private void buildDials() {
        Maneuver[] Advancedx1 = new Maneuver[18];
        Advancedx1[0] = new Maneuver(R.drawable.icon_maneuver_bank_left_blue, 1);
        Advancedx1[1] = new Maneuver(R.drawable.icon_maneuver_bank_right_blue, 1);
        Advancedx1[2] = new Maneuver(R.drawable.icon_maneuver_straight, 1);
        Advancedx1[3] = new Maneuver(R.drawable.icon_maneuver_turn_left, 2);
        Advancedx1[4] = new Maneuver(R.drawable.icon_maneuver_turn_right, 2);
        Advancedx1[5] = new Maneuver(R.drawable.icon_maneuver_straight_blue, 2);
        Advancedx1[6] = new Maneuver(R.drawable.icon_maneuver_bank_left_blue, 2);
        Advancedx1[7] = new Maneuver(R.drawable.icon_maneuver_bank_right_blue, 2);
        Advancedx1[8] = new Maneuver(R.drawable.icon_maneuver_turn_left, 3);
        Advancedx1[9] = new Maneuver(R.drawable.icon_maneuver_turn_right, 3);
        Advancedx1[10] = new Maneuver(R.drawable.icon_maneuver_bank_left, 3);
        Advancedx1[11] = new Maneuver(R.drawable.icon_maneuver_bank_right, 3);
        Advancedx1[12] = new Maneuver(R.drawable.icon_maneuver_straight_blue, 3);
        Advancedx1[13] = new Maneuver(R.drawable.icon_maneuver_tallon_left_red, 3);
        Advancedx1[14] = new Maneuver(R.drawable.icon_maneuver_tallon_right_red, 3);
        Advancedx1[15] = new Maneuver(R.drawable.icon_maneuver_straight, 4);
        Advancedx1[16] = new Maneuver(R.drawable.icon_maneuver_k_turn_red, 4);
        Advancedx1[17] = new Maneuver(R.drawable.icon_maneuver_straight, 5);
        fleet.put("TIE Advanced x1", Advancedx1);

        Maneuver[] Defender = new Maneuver[18];
        Defender[0] = new Maneuver(R.drawable.icon_maneuver_turn_left_red,1);
        Defender[1] = new Maneuver(R.drawable.icon_maneuver_turn_right_red,1);
        Defender[2] = new Maneuver(R.drawable.icon_maneuver_bank_left_blue,1);
        Defender[3] = new Maneuver(R.drawable.icon_maneuver_bank_right_blue,1);
        Defender[4] = new Maneuver(R.drawable.icon_maneuver_turn_left_red,2);
        Defender[5] = new Maneuver(R.drawable.icon_maneuver_turn_right_red,2);
        Defender[6] = new Maneuver(R.drawable.icon_maneuver_bank_left,2);
        Defender[7] = new Maneuver(R.drawable.icon_maneuver_bank_right,2);
        Defender[8] = new Maneuver(R.drawable.icon_maneuver_straight_blue,2);
        Defender[9] = new Maneuver(R.drawable.icon_maneuver_k_turn_red,2);
        Defender[10] = new Maneuver(R.drawable.icon_maneuver_turn_left,3);
        Defender[11] = new Maneuver(R.drawable.icon_maneuver_turn_right, 3);
        Defender[12] = new Maneuver(R.drawable.icon_maneuver_bank_left,3);
        Defender[13] = new Maneuver(R.drawable.icon_maneuver_bank_right,3);
        Defender[14] = new Maneuver(R.drawable.icon_maneuver_straight_blue, 3);
        Defender[15] = new Maneuver(R.drawable.icon_maneuver_straight_blue,4);
        Defender[16] = new Maneuver(R.drawable.icon_maneuver_k_turn,4);
        Defender[17] = new Maneuver(R.drawable.icon_maneuver_straight_blue,5);
        fleet.put("TIE Defender", Defender);

        Maneuver[] Line = new Maneuver[16];
        Line[0] = new Maneuver(R.drawable.icon_maneuver_turn_left,1);
        Line[1] = new Maneuver(R.drawable.icon_maneuver_turn_right,1);
        Line[2] = new Maneuver(R.drawable.icon_maneuver_turn_left,2);
        Line[3] = new Maneuver(R.drawable.icon_maneuver_turn_right,2);
        Line[4] = new Maneuver(R.drawable.icon_maneuver_bank_left_blue,2);
        Line[5] = new Maneuver(R.drawable.icon_maneuver_bank_right_blue,2);
        Line[6] = new Maneuver(R.drawable.icon_maneuver_straight_blue,2);
        Line[7] = new Maneuver(R.drawable.icon_maneuver_turn_left,3);
        Line[8] = new Maneuver(R.drawable.icon_maneuver_turn_right,3);
        Line[9] = new Maneuver(R.drawable.icon_maneuver_bank_left,3);
        Line[10] = new Maneuver(R.drawable.icon_maneuver_bank_right,3);
        Line[11] = new Maneuver(R.drawable.icon_maneuver_straight_blue,3);
        Line[12] = new Maneuver(R.drawable.icon_maneuver_k_turn_red,3);
        Line[13] = new Maneuver(R.drawable.icon_maneuver_straight,4);
        Line[14] = new Maneuver(R.drawable.icon_maneuver_k_turn_red,4);
        Line[15] = new Maneuver(R.drawable.icon_maneuver_straight,5);
        fleet.put("TIE/ln Fighter",Line);

        Maneuver[] LineFo = new Maneuver[17];
        LineFo[0] = new Maneuver(R.drawable.icon_maneuver_turn_left,1);
        LineFo[1] = new Maneuver(R.drawable.icon_maneuver_turn_right,1);
        LineFo[2] = new Maneuver(R.drawable.icon_maneuver_turn_left,2);
        LineFo[3] = new Maneuver(R.drawable.icon_maneuver_turn_right,2);
        LineFo[4] = new Maneuver(R.drawable.icon_maneuver_bank_left_blue,2);
        LineFo[5] = new Maneuver(R.drawable.icon_maneuver_bank_right_blue,2);
        LineFo[6] = new Maneuver(R.drawable.icon_maneuver_straight_blue,2);
        LineFo[7] = new Maneuver(R.drawable.icon_maneuver_segnor_left_red,2);
        LineFo[8] = new Maneuver(R.drawable.icon_maneuver_segnor_right_red,2);
        LineFo[9] = new Maneuver(R.drawable.icon_maneuver_turn_left,3);
        LineFo[10] = new Maneuver(R.drawable.icon_maneuver_turn_right,3);
        LineFo[11] = new Maneuver(R.drawable.icon_maneuver_bank_left,3);
        LineFo[12] = new Maneuver(R.drawable.icon_maneuver_bank_right,3);
        LineFo[13] = new Maneuver(R.drawable.icon_maneuver_straight_blue,3);
        LineFo[14] = new Maneuver(R.drawable.icon_maneuver_straight,4);
        LineFo[15] = new Maneuver(R.drawable.icon_maneuver_k_turn_red,4);
        LineFo[16] = new Maneuver(R.drawable.icon_maneuver_straight,5);
        fleet.put("TIE/fo Fighter",LineFo);

        Maneuver[] Striker = new Maneuver[16];
        Striker[0] = new Maneuver(R.drawable.icon_maneuver_turn_left, 1);
        Striker[1] = new Maneuver(R.drawable.icon_maneuver_turn_right, 1);
        Striker[2] = new Maneuver(R.drawable.icon_maneuver_bank_left_blue, 1);
        Striker[3] = new Maneuver(R.drawable.icon_maneuver_bank_right_blue, 1);
        Striker[4] = new Maneuver(R.drawable.icon_maneuver_straight_blue, 1);
        Striker[5] = new Maneuver(R.drawable.icon_maneuver_k_turn_red, 1);
        Striker[6] = new Maneuver(R.drawable.icon_maneuver_turn_left, 2);
        Striker[7] = new Maneuver(R.drawable.icon_maneuver_turn_right, 2);
        Striker[8] = new Maneuver(R.drawable.icon_maneuver_bank_left_blue, 2);
        Striker[9] = new Maneuver(R.drawable.icon_maneuver_bank_right_blue, 2);
        Striker[10] = new Maneuver(R.drawable.icon_maneuver_straight_blue, 2);
        Striker[11] = new Maneuver(R.drawable.icon_maneuver_segnor_left_red, 2);
        Striker[12] = new Maneuver(R.drawable.icon_maneuver_segnor_right_red, 2);
        Striker[13] = new Maneuver(R.drawable.icon_maneuver_bank_left, 3);
        Striker[14] = new Maneuver(R.drawable.icon_maneuver_bank_right, 3);
        Striker[15] = new Maneuver(R.drawable.icon_maneuver_straight_blue, 3);
        fleet.put("TIE Striker", Striker);

        Maneuver[] Phantom = new Maneuver[17];
        Phantom[0] = new Maneuver(R.drawable.icon_maneuver_turn_left,1);
        Phantom[1] = new Maneuver(R.drawable.icon_maneuver_turn_right,1);
        Phantom[2] = new Maneuver(R.drawable.icon_maneuver_bank_left,1);
        Phantom[3] = new Maneuver(R.drawable.icon_maneuver_bank_right,1);
        Phantom[4] = new Maneuver(R.drawable.icon_maneuver_turn_left,2);
        Phantom[5] = new Maneuver(R.drawable.icon_maneuver_turn_right,2);
        Phantom[6] = new Maneuver(R.drawable.icon_maneuver_bank_left_blue,2);
        Phantom[7] = new Maneuver(R.drawable.icon_maneuver_bank_right_blue,2);
        Phantom[8] = new Maneuver(R.drawable.icon_maneuver_straight_blue,2);
        Phantom[9] = new Maneuver(R.drawable.icon_maneuver_turn_left,3);
        Phantom[10] = new Maneuver(R.drawable.icon_maneuver_turn_right,3);
        Phantom[11] = new Maneuver(R.drawable.icon_maneuver_bank_left,3);
        Phantom[12] = new Maneuver(R.drawable.icon_maneuver_bank_right,3);
        Phantom[13] = new Maneuver(R.drawable.icon_maneuver_straight_blue,3);
        Phantom[14] = new Maneuver(R.drawable.icon_maneuver_k_turn_red, 3);
        Phantom[15] = new Maneuver(R.drawable.icon_maneuver_straight, 4);
        Phantom[16] = new Maneuver(R.drawable.icon_maneuver_k_turn_red, 4);
        fleet.put("TIE Phantom", Phantom);

        Maneuver[] TIE_Bomber = new Maneuver[16];
        TIE_Bomber[0] = new Maneuver(R.drawable.icon_maneuver_bank_left,1);
        TIE_Bomber[1] = new Maneuver(R.drawable.icon_maneuver_bank_right,1);
        TIE_Bomber[2] = new Maneuver(R.drawable.icon_maneuver_straight_blue,1);
        TIE_Bomber[3] = new Maneuver(R.drawable.icon_maneuver_turn_left,2);
        TIE_Bomber[4] = new Maneuver(R.drawable.icon_maneuver_turn_right,2);
        TIE_Bomber[5] = new Maneuver(R.drawable.icon_maneuver_bank_left_blue,2);
        TIE_Bomber[6] = new Maneuver(R.drawable.icon_maneuver_bank_right_blue,2);
        TIE_Bomber[7] = new Maneuver(R.drawable.icon_maneuver_straight_blue,2);
        TIE_Bomber[8] = new Maneuver(R.drawable.icon_maneuver_turn_left,3);
        TIE_Bomber[9] = new Maneuver(R.drawable.icon_maneuver_turn_right,3);
        TIE_Bomber[10] = new Maneuver(R.drawable.icon_maneuver_bank_left,3);
        TIE_Bomber[11] = new Maneuver(R.drawable.icon_maneuver_bank_right,3);
        TIE_Bomber[12] = new Maneuver(R.drawable.icon_maneuver_straight_blue,3);
        TIE_Bomber[13] = new Maneuver(R.drawable.icon_maneuver_k_turn_red,3);
        TIE_Bomber[14] = new Maneuver(R.drawable.icon_maneuver_straight_blue,4);
        TIE_Bomber[15] = new Maneuver(R.drawable.icon_maneuver_k_turn_red,5);
        fleet.put("TIE/sa Bomber", TIE_Bomber);

        Maneuver[] YT1300 = new Maneuver[17];
        YT1300[0] = new Maneuver(R.drawable.icon_maneuver_bank_left,1);
        YT1300[1] = new Maneuver(R.drawable.icon_maneuver_bank_right,1);
        YT1300[2] = new Maneuver(R.drawable.icon_maneuver_straight_blue,1);
        YT1300[3] = new Maneuver(R.drawable.icon_maneuver_turn_left,2);
        YT1300[4] = new Maneuver(R.drawable.icon_maneuver_turn_right,2);
        YT1300[5] = new Maneuver(R.drawable.icon_maneuver_bank_left_blue,2);
        YT1300[6] = new Maneuver(R.drawable.icon_maneuver_bank_right_blue,2);
        YT1300[7] = new Maneuver(R.drawable.icon_maneuver_straight_blue,2);
        YT1300[8] = new Maneuver(R.drawable.icon_maneuver_turn_left,3);
        YT1300[9] = new Maneuver(R.drawable.icon_maneuver_turn_right,3);
        YT1300[10] = new Maneuver(R.drawable.icon_maneuver_bank_left,3);
        YT1300[11] = new Maneuver(R.drawable.icon_maneuver_bank_right,3);
        YT1300[12] = new Maneuver(R.drawable.icon_maneuver_straight_blue,3);
        YT1300[13] = new Maneuver(R.drawable.icon_maneuver_segnor_left_red,3);
        YT1300[14] = new Maneuver(R.drawable.icon_maneuver_segnor_right_red,3);
        YT1300[15] = new Maneuver(R.drawable.icon_maneuver_straight,4);
        YT1300[16] = new Maneuver(R.drawable.icon_maneuver_k_turn_red,4);
        fleet.put("Modified YT-1300 Light Freighter", YT1300);

        Maneuver[] Auzituck_Gunship = new Maneuver[15];
        Auzituck_Gunship[0] = new Maneuver(R.drawable.icon_maneuver_stop_red, 0);
        Auzituck_Gunship[1] = new Maneuver(R.drawable.icon_maneuver_bank_left_blue, 1);
        Auzituck_Gunship[2] = new Maneuver(R.drawable.icon_maneuver_bank_right_blue, 1);
        Auzituck_Gunship[3] = new Maneuver(R.drawable.icon_maneuver_straight_blue, 1);
        Auzituck_Gunship[4] = new Maneuver(R.drawable.icon_maneuver_turn_left, 2);
        Auzituck_Gunship[5] = new Maneuver(R.drawable.icon_maneuver_turn_right, 2);
        Auzituck_Gunship[6] = new Maneuver(R.drawable.icon_maneuver_bank_left, 2);
        Auzituck_Gunship[7] = new Maneuver(R.drawable.icon_maneuver_bank_right, 2);
        Auzituck_Gunship[8] = new Maneuver(R.drawable.icon_maneuver_straight_blue, 2);
        Auzituck_Gunship[9] = new Maneuver(R.drawable.icon_maneuver_turn_left, 3);
        Auzituck_Gunship[10] = new Maneuver(R.drawable.icon_maneuver_turn_right, 3);
        Auzituck_Gunship[11] = new Maneuver(R.drawable.icon_maneuver_bank_left, 3);
        Auzituck_Gunship[12] = new Maneuver(R.drawable.icon_maneuver_bank_right, 3);
        Auzituck_Gunship[13] = new Maneuver(R.drawable.icon_maneuver_straight_blue, 3);
        Auzituck_Gunship[14] = new Maneuver(R.drawable.icon_maneuver_straight, 4);
        fleet.put("Auzituck Gunship", Auzituck_Gunship);

        Maneuver[] A_Wing = new Maneuver[17];
        A_Wing[0] = new Maneuver(R.drawable.icon_maneuver_turn_left,1);
        A_Wing[1] = new Maneuver(R.drawable.icon_maneuver_turn_right,1);
        A_Wing[2] = new Maneuver(R.drawable.icon_maneuver_turn_left_blue,2);
        A_Wing[3] = new Maneuver(R.drawable.icon_maneuver_turn_right_blue,2);
        A_Wing[4] = new Maneuver(R.drawable.icon_maneuver_bank_left_blue,2);
        A_Wing[5] = new Maneuver(R.drawable.icon_maneuver_bank_right_blue,2);
        A_Wing[6] = new Maneuver(R.drawable.icon_maneuver_straight_blue,2);
        A_Wing[7] = new Maneuver(R.drawable.icon_maneuver_turn_left,3);
        A_Wing[8] = new Maneuver(R.drawable.icon_maneuver_turn_right,3);
        A_Wing[9] = new Maneuver(R.drawable.icon_maneuver_bank_left,3);
        A_Wing[10] = new Maneuver(R.drawable.icon_maneuver_bank_right,3);
        A_Wing[11] = new Maneuver(R.drawable.icon_maneuver_straight_blue,3);
        A_Wing[12] = new Maneuver(R.drawable.icon_maneuver_segnor_left_red,3);
        A_Wing[13] = new Maneuver(R.drawable.icon_maneuver_segnor_right_red,3);
        A_Wing[14] = new Maneuver(R.drawable.icon_maneuver_straight_blue, 4);
        A_Wing[15] = new Maneuver(R.drawable.icon_maneuver_straight_blue, 5);
        A_Wing[16] = new Maneuver(R.drawable.icon_maneuver_k_turn_red, 5);
        fleet.put("RZ-1 A-Wing", A_Wing);

        Maneuver[] X_Wing = new Maneuver[17];
        X_Wing[0] = new Maneuver(R.drawable.icon_maneuver_bank_left_blue,1);
        X_Wing[1] = new Maneuver(R.drawable.icon_maneuver_bank_right_blue, 1);
        X_Wing[2] = new Maneuver(R.drawable.icon_maneuver_straight,1);
        X_Wing[3] = new Maneuver(R.drawable.icon_maneuver_turn_left,2);
        X_Wing[4] = new Maneuver(R.drawable.icon_maneuver_turn_right, 2);
        X_Wing[5] = new Maneuver(R.drawable.icon_maneuver_bank_left_blue,2);
        X_Wing[6] = new Maneuver(R.drawable.icon_maneuver_bank_right_blue,2);
        X_Wing[7] = new Maneuver(R.drawable.icon_maneuver_straight_blue,2);
        X_Wing[8] = new Maneuver(R.drawable.icon_maneuver_turn_left,3);
        X_Wing[9] = new Maneuver(R.drawable.icon_maneuver_turn_right,3);
        X_Wing[10] = new Maneuver(R.drawable.icon_maneuver_bank_left,3);
        X_Wing[11] = new Maneuver(R.drawable.icon_maneuver_bank_right,3);
        X_Wing[12] = new Maneuver(R.drawable.icon_maneuver_straight,3);
        X_Wing[13] = new Maneuver(R.drawable.icon_maneuver_tallon_left_red,3);
        X_Wing[14] = new Maneuver(R.drawable.icon_maneuver_tallon_right_red,3);
        X_Wing[15] = new Maneuver(R.drawable.icon_maneuver_straight, 4);
        X_Wing[16] = new Maneuver(R.drawable.icon_maneuver_k_turn_red, 4);
        fleet.put("T-65 X-Wing", X_Wing);

        Maneuver[] T70_X_Wing = new Maneuver[17];
        T70_X_Wing[0] = new Maneuver(R.drawable.icon_maneuver_bank_left_blue,1);
        T70_X_Wing[1] = new Maneuver(R.drawable.icon_maneuver_bank_right_blue, 1);
        T70_X_Wing[2] = new Maneuver(R.drawable.icon_maneuver_straight,1);
        T70_X_Wing[3] = new Maneuver(R.drawable.icon_maneuver_turn_left,2);
        T70_X_Wing[4] = new Maneuver(R.drawable.icon_maneuver_turn_right, 2);
        T70_X_Wing[5] = new Maneuver(R.drawable.icon_maneuver_bank_left_blue,2);
        T70_X_Wing[6] = new Maneuver(R.drawable.icon_maneuver_bank_right_blue,2);
        T70_X_Wing[7] = new Maneuver(R.drawable.icon_maneuver_straight_blue,2);
        T70_X_Wing[8] = new Maneuver(R.drawable.icon_maneuver_turn_left,3);
        T70_X_Wing[9] = new Maneuver(R.drawable.icon_maneuver_turn_right,3);
        T70_X_Wing[10] = new Maneuver(R.drawable.icon_maneuver_bank_left,3);
        T70_X_Wing[11] = new Maneuver(R.drawable.icon_maneuver_bank_right,3);
        T70_X_Wing[12] = new Maneuver(R.drawable.icon_maneuver_straight_blue,3);
        T70_X_Wing[13] = new Maneuver(R.drawable.icon_maneuver_tallon_left_red,3);
        T70_X_Wing[14] = new Maneuver(R.drawable.icon_maneuver_tallon_right_red,3);
        T70_X_Wing[15] = new Maneuver(R.drawable.icon_maneuver_straight, 4);
        T70_X_Wing[16] = new Maneuver(R.drawable.icon_maneuver_k_turn_red, 4);
        fleet.put("T-70 X-Wing", T70_X_Wing);

        Maneuver[] Y_Wing = new Maneuver[15];
        Y_Wing[0] = new Maneuver(R.drawable.icon_maneuver_bank_left_blue,1);
        Y_Wing[1] = new Maneuver(R.drawable.icon_maneuver_bank_right_blue,1);
        Y_Wing[2] = new Maneuver(R.drawable.icon_maneuver_straight_blue,1);
        Y_Wing[3] = new Maneuver(R.drawable.icon_maneuver_turn_left,2);
        Y_Wing[4] = new Maneuver(R.drawable.icon_maneuver_turn_right, 2);
        Y_Wing[5] = new Maneuver(R.drawable.icon_maneuver_bank_left,2);
        Y_Wing[6] = new Maneuver(R.drawable.icon_maneuver_bank_right,2);
        Y_Wing[7] = new Maneuver(R.drawable.icon_maneuver_straight_blue,2);
        Y_Wing[8] = new Maneuver(R.drawable.icon_maneuver_turn_left_red,3);
        Y_Wing[9] = new Maneuver(R.drawable.icon_maneuver_turn_right_red,3);
        Y_Wing[10] = new Maneuver(R.drawable.icon_maneuver_bank_left,3);
        Y_Wing[11] = new Maneuver(R.drawable.icon_maneuver_bank_right,3);
        Y_Wing[12] = new Maneuver(R.drawable.icon_maneuver_straight,3);
        Y_Wing[13] = new Maneuver(R.drawable.icon_maneuver_straight_red,4);
        Y_Wing[14] = new Maneuver(R.drawable.icon_maneuver_k_turn_red,4);
        fleet.put("BTL-A4 Y-Wing", Y_Wing);

        Maneuver[] B_Wing = new Maneuver[16];
        B_Wing[0] = new Maneuver(R.drawable.icon_maneuver_turn_left_red,1);
        B_Wing[1] = new Maneuver(R.drawable.icon_maneuver_turn_right_red,1);
        B_Wing[2] = new Maneuver(R.drawable.icon_maneuver_bank_left_blue,1);
        B_Wing[3] = new Maneuver(R.drawable.icon_maneuver_bank_right_blue,1);
        B_Wing[4] = new Maneuver(R.drawable.icon_maneuver_straight_blue,1);
        B_Wing[5] = new Maneuver(R.drawable.icon_maneuver_tallon_left_red,1);
        B_Wing[6] = new Maneuver(R.drawable.icon_maneuver_tallon_right_red,1);
        B_Wing[7] = new Maneuver(R.drawable.icon_maneuver_turn_left,2);
        B_Wing[8] = new Maneuver(R.drawable.icon_maneuver_turn_right,2);
        B_Wing[9] = new Maneuver(R.drawable.icon_maneuver_bank_left,2);
        B_Wing[10] = new Maneuver(R.drawable.icon_maneuver_bank_right,2);
        B_Wing[11] = new Maneuver(R.drawable.icon_maneuver_straight_blue,2);
        B_Wing[12] = new Maneuver(R.drawable.icon_maneuver_k_turn_red,2);
        B_Wing[13] = new Maneuver(R.drawable.icon_maneuver_bank_left_red,3);
        B_Wing[14] = new Maneuver(R.drawable.icon_maneuver_bank_right_red,3);
        B_Wing[15] = new Maneuver(R.drawable.icon_maneuver_straight_red,4);
        fleet.put("A/SF-01 B-Wing", B_Wing);
    }

    public Maneuver[] getDial(String name){
        return this.fleet.get(name);
    }
}